// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGitHubOAuth(arg1) {
  return window['go']['main']['App']['CheckGitHubOAuth'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function ClearGitHubAuth() {
  return window['go']['main']['App']['ClearGitHubAuth']();
}

export function DetectAgents() {
  return window['go']['main']['App']['DetectAgents']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetGitHubRateLimit() {
  return window['go']['main']['App']['GetGitHubRateLimit']();
}

export function InstallLocalSkill(arg1) {
  return window['go']['main']['App']['InstallLocalSkill'](arg1);
}

export function InstallSkill(arg1) {
  return window['go']['main']['App']['InstallSkill'](arg1);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListRepositorySkills(arg1) {
  return window['go']['main']['App']['ListRepositorySkills'](arg1);
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function PickAgentSkillsDir() {
  return window['go']['main']['App']['PickAgentSkillsDir']();
}

export function PickLocalDirectory() {
  return window['go']['main']['App']['PickLocalDirectory']();
}

export function PickLocalSkillFile() {
  return window['go']['main']['App']['PickLocalSkillFile']();
}

export function ScanRepository(arg1) {
  return window['go']['main']['App']['ScanRepository'](arg1);
}

export function SetAgentEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAgentEnabled'](arg1, arg2);
}

export function SetAgentSkillsPath(arg1, arg2) {
  return window['go']['main']['App']['SetAgentSkillsPath'](arg1, arg2);
}

export function SetDownloadMirror(arg1) {
  return window['go']['main']['App']['SetDownloadMirror'](arg1);
}

export function SetGitHubToken(arg1) {
  return window['go']['main']['App']['SetGitHubToken'](arg1);
}

export function SetSharedDir(arg1) {
  return window['go']['main']['App']['SetSharedDir'](arg1);
}

export function StartGitHubOAuth() {
  return window['go']['main']['App']['StartGitHubOAuth']();
}

export function UninstallSkill(arg1) {
  return window['go']['main']['App']['UninstallSkill'](arg1);
}

export function UpdateSkill(arg1) {
  return window['go']['main']['App']['UpdateSkill'](arg1);
}

export function UpdateSkillNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateSkillNote'](arg1, arg2);
}
