// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function CheckGitHubOAuth(arg1:string):Promise<Record<string, string>>;

export function CheckUpdate(arg1:string):Promise<main.CheckUpdateResult>;

export function ClearGitHubAuth():Promise<void>;

export function DetectAgents():Promise<Array<models.Agent>>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetGitHubRateLimit():Promise<Record<string, any>>;

export function InstallLocalSkill(arg1:string):Promise<main.LocalInstallResult>;

export function InstallSkill(arg1:main.InstallRequest):Promise<main.InstallResult>;

export function ListAgents():Promise<Array<models.Agent>>;

export function ListRepositorySkills(arg1:string):Promise<Array<main.RepoSkill>>;

export function ListSkills():Promise<Array<models.Skill>>;

export function PickAgentSkillsDir():Promise<string>;

export function PickLocalDirectory():Promise<string>;

export function PickLocalSkillFile():Promise<string>;

export function ScanRepository(arg1:string):Promise<main.ScanResult>;

export function SetAgentEnabled(arg1:string,arg2:boolean):Promise<Array<models.Agent>>;

export function SetAgentSkillsPath(arg1:string,arg2:string):Promise<Array<models.Agent>>;

export function SetDownloadMirror(arg1:string):Promise<void>;

export function SetGitHubToken(arg1:string):Promise<void>;

export function SetSharedDir(arg1:string):Promise<void>;

export function StartGitHubOAuth():Promise<Record<string, string>>;

export function UninstallSkill(arg1:string):Promise<main.UninstallResult>;

export function UpdateSkill(arg1:string):Promise<main.InstallResult>;

export function UpdateSkillNote(arg1:string,arg2:string):Promise<void>;
